// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebServerFinalProject.Data;

#nullable disable

namespace WebServerFinalProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251126185226_AddRecipeInstructions")]
    partial class AddRecipeInstructions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebServerFinalProject.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Spring"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Fall"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Holiday"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Summer"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Winter"
                        });
                });

            modelBuilder.Entity("WebServerFinalProject.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            Name = "Flour"
                        },
                        new
                        {
                            IngredientId = 2,
                            Name = "Sugar"
                        },
                        new
                        {
                            IngredientId = 3,
                            Name = "Eggs"
                        },
                        new
                        {
                            IngredientId = 4,
                            Name = "Butter"
                        },
                        new
                        {
                            IngredientId = 5,
                            Name = "Vanilla Extract"
                        },
                        new
                        {
                            IngredientId = 6,
                            Name = "Baking Powder"
                        },
                        new
                        {
                            IngredientId = 7,
                            Name = "Cinnamon"
                        },
                        new
                        {
                            IngredientId = 8,
                            Name = "Strawberries"
                        },
                        new
                        {
                            IngredientId = 9,
                            Name = "Whipped Cream"
                        },
                        new
                        {
                            IngredientId = 10,
                            Name = "Lemons"
                        },
                        new
                        {
                            IngredientId = 11,
                            Name = "Yeast"
                        },
                        new
                        {
                            IngredientId = 12,
                            Name = "Brown Sugar"
                        },
                        new
                        {
                            IngredientId = 13,
                            Name = "Cream Cheese"
                        },
                        new
                        {
                            IngredientId = 14,
                            Name = "Bananas"
                        },
                        new
                        {
                            IngredientId = 15,
                            Name = "Milk"
                        },
                        new
                        {
                            IngredientId = 16,
                            Name = "Chocolate Chips"
                        },
                        new
                        {
                            IngredientId = 17,
                            Name = "Heavy Cream"
                        },
                        new
                        {
                            IngredientId = 18,
                            Name = "Graham Cracker Crumbs"
                        });
                });

            modelBuilder.Entity("WebServerFinalProject.Models.Recipe", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BakeMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrepMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BakeMinutes = 30,
                            CategoryId = 3,
                            Description = "A simple chocolate cake anyone can bake.",
                            Difficulty = "Easy",
                            Instructions = "1. Preheat oven to 350°F (175°C).\n2. Whisk flour, sugar, cocoa, and baking powder.\n3. Add eggs, melted butter, milk, and vanilla.\n4. Pour into a greased pan.\n5. Bake 30 minutes or until a toothpick comes out clean.\n6. Let cool before slicing.",
                            PrepMinutes = 15,
                            Title = "Chocolate Cake",
                            Type = "Cake"
                        },
                        new
                        {
                            ID = 2,
                            BakeMinutes = 40,
                            CategoryId = 2,
                            Description = "A beginner-friendly apple pie with a simple filling.",
                            Difficulty = "Medium",
                            Instructions = "1. Preheat oven to 375°F (190°C).\n2. Mix sliced apples with sugar and cinnamon.\n3. Place mixture into pie crust.\n4. Add top crust and cut small slits.\n5. Bake 40 minutes or until crust is golden.\n6. Cool 10 minutes before serving.",
                            PrepMinutes = 20,
                            Title = "Classic Apple Pie",
                            Type = "Pie"
                        },
                        new
                        {
                            ID = 3,
                            BakeMinutes = 50,
                            CategoryId = 2,
                            Description = "A soft, cozy pumpkin loaf made in one bowl.",
                            Difficulty = "Easy",
                            Instructions = "1. Preheat oven to 350°F (175°C).\n2. Stir flour, sugar, cinnamon, and baking powder.\n3. Add eggs, melted butter, milk, and pumpkin.\n4. Pour into a greased loaf pan.\n5. Bake 50 minutes or until set.\n6. Cool before slicing.",
                            PrepMinutes = 15,
                            Title = "Easy Pumpkin Bread",
                            Type = "Bread"
                        },
                        new
                        {
                            ID = 4,
                            BakeMinutes = 0,
                            CategoryId = 1,
                            Description = "Light and simple layered strawberry dessert.",
                            Difficulty = "Easy",
                            Instructions = "1. Slice strawberries and mix with a little sugar.\n2. Crumble shortcake or vanilla cake.\n3. Layer cake, berries, and whipped cream in cups.\n4. Repeat layers.\n5. Chill for 10 minutes and serve.",
                            PrepMinutes = 10,
                            Title = "Strawberry Shortcake Cups",
                            Type = "Dessert"
                        },
                        new
                        {
                            ID = 5,
                            BakeMinutes = 25,
                            CategoryId = 4,
                            Description = "Simple lemon bars with a buttery crust.",
                            Difficulty = "Easy",
                            Instructions = "1. Preheat oven to 350°F (175°C).\n2. Mix crust: flour, sugar, melted butter.\n3. Press crust into a pan and bake 10 minutes.\n4. Whisk lemon juice, sugar, eggs, and flour.\n5. Pour over warm crust.\n6. Bake 15 more minutes and cool before cutting.",
                            PrepMinutes = 15,
                            Title = "Lemon Bars",
                            Type = "Dessert"
                        },
                        new
                        {
                            ID = 6,
                            BakeMinutes = 20,
                            CategoryId = 4,
                            Description = "Soft cinnamon rolls made with basic dough.",
                            Difficulty = "Medium",
                            Instructions = "1. Mix flour, yeast, sugar, milk, and butter into soft dough.\n2. Roll the dough into a rectangle.\n3. Spread butter, cinnamon, and sugar.\n4. Roll up and slice into spirals.\n5. Bake 20 minutes at 350°F.\n6. Add icing if desired.",
                            PrepMinutes = 25,
                            Title = "Simple Cinnamon Rolls",
                            Type = "Bread"
                        },
                        new
                        {
                            ID = 7,
                            BakeMinutes = 12,
                            CategoryId = 2,
                            Description = "Soft, chewy cookies rolled in cinnamon sugar.",
                            Difficulty = "Easy",
                            Instructions = "1. Cream butter and sugar.\n2. Add eggs and vanilla.\n3. Stir in flour, baking powder, and cinnamon.\n4. Roll dough into balls.\n5. Coat in cinnamon sugar.\n6. Bake 12 minutes at 350°F.",
                            PrepMinutes = 15,
                            Title = "Cinnamon Sugar Cookies",
                            Type = "Cookies"
                        },
                        new
                        {
                            ID = 8,
                            BakeMinutes = 18,
                            CategoryId = 3,
                            Description = "Beginner-friendly yeast rolls for any holiday.",
                            Difficulty = "Medium",
                            Instructions = "1. Combine flour, yeast, milk, sugar, and butter.\n2. Knead 5 minutes.\n3. Let rise 1 hour.\n4. Shape into rolls.\n5. Bake 18 minutes at 350°F.\n6. Brush with melted butter.",
                            PrepMinutes = 20,
                            Title = "Soft Dinner Rolls",
                            Type = "Bread"
                        },
                        new
                        {
                            ID = 9,
                            BakeMinutes = 50,
                            CategoryId = 5,
                            Description = "A simple, moist banana bread anyone can make.",
                            Difficulty = "Easy",
                            Instructions = "1. Mash ripe bananas.\n2. Stir in sugar, eggs, and melted butter.\n3. Add flour and baking powder.\n4. Pour into a loaf pan.\n5. Bake 50 minutes at 350°F.\n6. Cool completely before slicing.",
                            PrepMinutes = 10,
                            Title = "Banana Bread",
                            Type = "Bread"
                        },
                        new
                        {
                            ID = 10,
                            BakeMinutes = 0,
                            CategoryId = 3,
                            Description = "An easy no-bake tart with a basic ganache filling.",
                            Difficulty = "Medium",
                            Instructions = "1. Mix graham crumbs and melted butter.\n2. Press into a tart pan and chill.\n3. Heat cream until warm.\n4. Stir in chocolate chips until smooth.\n5. Pour into crust.\n6. Chill 1 hour before serving.",
                            PrepMinutes = 20,
                            Title = "No-Bake Chocolate Tart",
                            Type = "Dessert"
                        });
                });

            modelBuilder.Entity("WebServerFinalProject.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 1,
                            Quantity = 2.0,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 2,
                            Quantity = 1.5,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 3,
                            Quantity = 3.0,
                            Unit = "pcs"
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 4,
                            Quantity = 0.5,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 5,
                            Quantity = 2.0,
                            Unit = "tsp"
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 1,
                            Quantity = 3.0,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 2,
                            Quantity = 1.0,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 12,
                            Quantity = 0.5,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 4,
                            Quantity = 0.75,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 7,
                            Quantity = 1.0,
                            Unit = "tsp"
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 1,
                            Quantity = 2.0,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 2,
                            Quantity = 1.0,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 3,
                            Quantity = 2.0,
                            Unit = "pcs"
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 7,
                            Quantity = 2.0,
                            Unit = "tsp"
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 6,
                            Quantity = 2.0,
                            Unit = "tsp"
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 8,
                            Quantity = 1.5,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 9,
                            Quantity = 1.0,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 1,
                            Quantity = 1.0,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 2,
                            Quantity = 0.5,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 10,
                            Quantity = 3.0,
                            Unit = "pcs"
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 2,
                            Quantity = 1.0,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 1,
                            Quantity = 1.5,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 4,
                            Quantity = 0.5,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 1,
                            Quantity = 3.0,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 11,
                            Quantity = 2.0,
                            Unit = "tsp"
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 12,
                            Quantity = 0.5,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 7,
                            Quantity = 2.0,
                            Unit = "tsp"
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 15,
                            Quantity = 1.0,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 7,
                            IngredientId = 1,
                            Quantity = 2.0,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 7,
                            IngredientId = 2,
                            Quantity = 1.0,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 7,
                            IngredientId = 4,
                            Quantity = 0.5,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 7,
                            IngredientId = 7,
                            Quantity = 1.0,
                            Unit = "tsp"
                        },
                        new
                        {
                            RecipeId = 7,
                            IngredientId = 3,
                            Quantity = 2.0,
                            Unit = "pcs"
                        },
                        new
                        {
                            RecipeId = 8,
                            IngredientId = 1,
                            Quantity = 3.0,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 8,
                            IngredientId = 11,
                            Quantity = 2.0,
                            Unit = "tsp"
                        },
                        new
                        {
                            RecipeId = 8,
                            IngredientId = 2,
                            Quantity = 0.25,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 8,
                            IngredientId = 4,
                            Quantity = 0.25,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 8,
                            IngredientId = 15,
                            Quantity = 1.0,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 9,
                            IngredientId = 14,
                            Quantity = 3.0,
                            Unit = "pcs"
                        },
                        new
                        {
                            RecipeId = 9,
                            IngredientId = 1,
                            Quantity = 2.0,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 9,
                            IngredientId = 2,
                            Quantity = 1.0,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 9,
                            IngredientId = 3,
                            Quantity = 2.0,
                            Unit = "pcs"
                        },
                        new
                        {
                            RecipeId = 9,
                            IngredientId = 6,
                            Quantity = 1.0,
                            Unit = "tsp"
                        },
                        new
                        {
                            RecipeId = 10,
                            IngredientId = 16,
                            Quantity = 2.0,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 10,
                            IngredientId = 17,
                            Quantity = 1.0,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 10,
                            IngredientId = 18,
                            Quantity = 1.5,
                            Unit = "cups"
                        });
                });

            modelBuilder.Entity("WebServerFinalProject.Models.Recipe", b =>
                {
                    b.HasOne("WebServerFinalProject.Models.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebServerFinalProject.Models.RecipeIngredient", b =>
                {
                    b.HasOne("WebServerFinalProject.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebServerFinalProject.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("WebServerFinalProject.Models.Category", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("WebServerFinalProject.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("WebServerFinalProject.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
