// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebServerFinalProject.Data;

#nullable disable

namespace WebServerFinalProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251126183433_UpdateBasicBakingRecipes")]
    partial class UpdateBasicBakingRecipes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebServerFinalProject.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Spring"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Fall"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Holiday"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Summer"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Winter"
                        });
                });

            modelBuilder.Entity("WebServerFinalProject.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            Name = "Flour"
                        },
                        new
                        {
                            IngredientId = 2,
                            Name = "Sugar"
                        },
                        new
                        {
                            IngredientId = 3,
                            Name = "Eggs"
                        },
                        new
                        {
                            IngredientId = 4,
                            Name = "Butter"
                        },
                        new
                        {
                            IngredientId = 5,
                            Name = "Vanilla Extract"
                        },
                        new
                        {
                            IngredientId = 6,
                            Name = "Baking Powder"
                        },
                        new
                        {
                            IngredientId = 7,
                            Name = "Cinnamon"
                        },
                        new
                        {
                            IngredientId = 8,
                            Name = "Strawberries"
                        },
                        new
                        {
                            IngredientId = 9,
                            Name = "Whipped Cream"
                        },
                        new
                        {
                            IngredientId = 10,
                            Name = "Lemons"
                        },
                        new
                        {
                            IngredientId = 11,
                            Name = "Yeast"
                        },
                        new
                        {
                            IngredientId = 12,
                            Name = "Brown Sugar"
                        },
                        new
                        {
                            IngredientId = 13,
                            Name = "Cream Cheese"
                        },
                        new
                        {
                            IngredientId = 14,
                            Name = "Bananas"
                        },
                        new
                        {
                            IngredientId = 15,
                            Name = "Milk"
                        },
                        new
                        {
                            IngredientId = 16,
                            Name = "Chocolate Chips"
                        },
                        new
                        {
                            IngredientId = 17,
                            Name = "Heavy Cream"
                        },
                        new
                        {
                            IngredientId = 18,
                            Name = "Graham Cracker Crumbs"
                        });
                });

            modelBuilder.Entity("WebServerFinalProject.Models.Recipe", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BakeMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrepMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BakeMinutes = 30,
                            CategoryId = 3,
                            Description = "Whisk together the batter, pour into a pan, and bake until a toothpick comes out clean.",
                            Difficulty = "Medium",
                            PrepMinutes = 15,
                            Title = "Chocolate Cake",
                            Type = "Cake"
                        },
                        new
                        {
                            ID = 2,
                            BakeMinutes = 40,
                            CategoryId = 2,
                            Description = "Fill a basic pie crust with spiced apples, add caramel, and bake until golden and bubbly.",
                            Difficulty = "Medium",
                            PrepMinutes = 20,
                            Title = "Caramel Apple Pie",
                            Type = "Pie"
                        },
                        new
                        {
                            ID = 3,
                            BakeMinutes = 50,
                            CategoryId = 2,
                            Description = "Stir a simple pumpkin batter together in one bowl and bake until the loaf is set in the center.",
                            Difficulty = "Easy",
                            PrepMinutes = 15,
                            Title = "Pumpkin Bread",
                            Type = "Bread"
                        },
                        new
                        {
                            ID = 4,
                            BakeMinutes = 0,
                            CategoryId = 1,
                            Description = "Layer bite-size cake pieces, sweet berries, and whipped cream into small serving cups.",
                            Difficulty = "Easy",
                            PrepMinutes = 15,
                            Title = "Strawberry Shortcake Cups",
                            Type = "Dessert"
                        },
                        new
                        {
                            ID = 5,
                            BakeMinutes = 25,
                            CategoryId = 4,
                            Description = "Press a simple crust into a pan, pour on the lemon filling, and bake until just set.",
                            Difficulty = "Easy",
                            PrepMinutes = 15,
                            Title = "Lemon Bars",
                            Type = "Dessert"
                        },
                        new
                        {
                            ID = 6,
                            BakeMinutes = 20,
                            CategoryId = 4,
                            Description = "Mix a soft dough, roll it with cinnamon sugar, slice, and bake until fluffy and golden.",
                            Difficulty = "Medium",
                            PrepMinutes = 25,
                            Title = "Cinnamon Rolls",
                            Type = "Bread"
                        },
                        new
                        {
                            ID = 7,
                            BakeMinutes = 12,
                            CategoryId = 2,
                            Description = "Cream butter and sugar, roll the dough into balls, coat in cinnamon sugar, and bake.",
                            Difficulty = "Easy",
                            PrepMinutes = 15,
                            Title = "Cinnamon Sugar Cookies",
                            Type = "Cookies"
                        },
                        new
                        {
                            ID = 8,
                            BakeMinutes = 18,
                            CategoryId = 3,
                            Description = "Let a simple yeast dough rise, shape into rolls, and bake until lightly browned.",
                            Difficulty = "Medium",
                            PrepMinutes = 20,
                            Title = "Holiday Dinner Rolls",
                            Type = "Bread"
                        },
                        new
                        {
                            ID = 9,
                            BakeMinutes = 50,
                            CategoryId = 5,
                            Description = "Mash ripe bananas, stir in the batter, and bake until the loaf is browned and fragrant.",
                            Difficulty = "Easy",
                            PrepMinutes = 15,
                            Title = "Banana Bread",
                            Type = "Bread"
                        },
                        new
                        {
                            ID = 10,
                            BakeMinutes = 0,
                            CategoryId = 3,
                            Description = "Press crumbs into a tart pan, chill, then fill with a simple chocolate ganache and let it set.",
                            Difficulty = "Hard",
                            PrepMinutes = 20,
                            Title = "Chocolate Ganache Tart",
                            Type = "Dessert"
                        });
                });

            modelBuilder.Entity("WebServerFinalProject.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 1,
                            Quantity = 2.0,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 2,
                            Quantity = 1.5,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 3,
                            Quantity = 3.0,
                            Unit = "pcs"
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 4,
                            Quantity = 0.5,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 5,
                            Quantity = 2.0,
                            Unit = "tsp"
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 1,
                            Quantity = 3.0,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 2,
                            Quantity = 1.0,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 12,
                            Quantity = 0.5,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 4,
                            Quantity = 0.75,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 7,
                            Quantity = 1.0,
                            Unit = "tsp"
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 1,
                            Quantity = 2.0,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 2,
                            Quantity = 1.0,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 3,
                            Quantity = 2.0,
                            Unit = "pcs"
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 7,
                            Quantity = 2.0,
                            Unit = "tsp"
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 6,
                            Quantity = 2.0,
                            Unit = "tsp"
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 8,
                            Quantity = 1.5,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 9,
                            Quantity = 1.0,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 1,
                            Quantity = 1.0,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 2,
                            Quantity = 0.5,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 10,
                            Quantity = 3.0,
                            Unit = "pcs"
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 2,
                            Quantity = 1.0,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 1,
                            Quantity = 1.5,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 4,
                            Quantity = 0.5,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 1,
                            Quantity = 3.0,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 11,
                            Quantity = 2.0,
                            Unit = "tsp"
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 12,
                            Quantity = 0.5,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 7,
                            Quantity = 2.0,
                            Unit = "tsp"
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 15,
                            Quantity = 1.0,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 7,
                            IngredientId = 1,
                            Quantity = 2.0,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 7,
                            IngredientId = 2,
                            Quantity = 1.0,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 7,
                            IngredientId = 4,
                            Quantity = 0.5,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 7,
                            IngredientId = 7,
                            Quantity = 1.0,
                            Unit = "tsp"
                        },
                        new
                        {
                            RecipeId = 7,
                            IngredientId = 3,
                            Quantity = 2.0,
                            Unit = "pcs"
                        },
                        new
                        {
                            RecipeId = 8,
                            IngredientId = 1,
                            Quantity = 3.0,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 8,
                            IngredientId = 11,
                            Quantity = 2.0,
                            Unit = "tsp"
                        },
                        new
                        {
                            RecipeId = 8,
                            IngredientId = 2,
                            Quantity = 0.25,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 8,
                            IngredientId = 4,
                            Quantity = 0.25,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 8,
                            IngredientId = 15,
                            Quantity = 1.0,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 9,
                            IngredientId = 14,
                            Quantity = 3.0,
                            Unit = "pcs"
                        },
                        new
                        {
                            RecipeId = 9,
                            IngredientId = 1,
                            Quantity = 2.0,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 9,
                            IngredientId = 2,
                            Quantity = 1.0,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 9,
                            IngredientId = 3,
                            Quantity = 2.0,
                            Unit = "pcs"
                        },
                        new
                        {
                            RecipeId = 9,
                            IngredientId = 6,
                            Quantity = 1.0,
                            Unit = "tsp"
                        },
                        new
                        {
                            RecipeId = 10,
                            IngredientId = 16,
                            Quantity = 2.0,
                            Unit = "cups"
                        },
                        new
                        {
                            RecipeId = 10,
                            IngredientId = 17,
                            Quantity = 1.0,
                            Unit = "cup"
                        },
                        new
                        {
                            RecipeId = 10,
                            IngredientId = 18,
                            Quantity = 1.5,
                            Unit = "cups"
                        });
                });

            modelBuilder.Entity("WebServerFinalProject.Models.Recipe", b =>
                {
                    b.HasOne("WebServerFinalProject.Models.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebServerFinalProject.Models.RecipeIngredient", b =>
                {
                    b.HasOne("WebServerFinalProject.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebServerFinalProject.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("WebServerFinalProject.Models.Category", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("WebServerFinalProject.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("WebServerFinalProject.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
